export const TRANSACTION_STATUS = {
  SCHEDULED: "AGENDADO",
  PENDING: "PENDENTE",
  PROCESSING: "PROCESSANDO",
  CONFIRMED: "APROVADO",
  CANCELED: "CANCELADO"
} as const

export const TRANSACTION_TYPE = {
  TRANSFER: "TRANSFERÊNCIA",
  PAYMENT: "PAGAMENTO",
  DEPOSIT: "DEPÓSITO",
} as const