version: "3.6"

x-shared-environment: &shared-environment
  restart: unless-stopped
  networks:
    - garupa_network

services:
  server:
    <<: *shared-environment
    image: garupa-server
    environment:
      DB_URL: postgres
    build:
      context: ./server
      dockerfile: docker/Dockerfile
    command: npm run start
    volumes:
      - ./server:/app/
    ports:
      - 3000:3000
  
  postgres:
    <<: *shared-environment
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: garupa
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
  
  # webapp:
  #   <<: *shared-environment
  #   image: garupa-webapp
  #   build:
  #     context: ./webapp
  #     dockerfile: docker/Dockerfile
  #   # command: npm run dev
  #   volumes:
  #     - ./webapp:/app/
  #   ports:
  #     - 80:80

volumes:
  postgres-data:

networks:
  garupa_network:
    external: true